using System;
using System.ComponentModel;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Bunifu.UI.WinForms;
using Bunifu.UI.WinForms.BunifuButton;
using Siticone.Desktop.UI.WinForms;

namespace tylowprivate
{
    partial class Form1
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(Form1));
            BunifuButton2.BorderEdges borderEdges = new BunifuButton2.BorderEdges();
            BunifuButton2.BorderEdges borderEdges2 = new BunifuButton2.BorderEdges();
            BunifuButton2.BorderEdges borderEdges3 = new BunifuButton2.BorderEdges();
            BunifuButton2.BorderEdges borderEdges4 = new BunifuButton2.BorderEdges();
            BunifuButton2.BorderEdges borderEdges5 = new BunifuButton2.BorderEdges();
            BunifuButton2.BorderEdges borderEdges6 = new BunifuButton2.BorderEdges();
            BunifuButton2.BorderEdges borderEdges7 = new BunifuButton2.BorderEdges();
            this.label1 = new Label();
            this.siticonePanel1 = new SiticonePanel();
            this.bunifuButton27 = new BunifuButton2();
            this.bunifuButton26 = new BunifuButton2();
            this.bunifuButton25 = new BunifuButton2();
            this.bunifuHScrollBar3 = new BunifuHScrollBar();
            this.label8 = new Label();
            this.bunifuHScrollBar2 = new BunifuHScrollBar();
            this.label6 = new Label();
            this.bunifuHScrollBar1 = new BunifuHScrollBar();
            this.label3 = new Label();
            this.bunifuButton22 = new BunifuButton2();
            this.bunifuButton21 = new BunifuButton2();
            this.label2 = new Label();
            this.siticonePanel2 = new SiticonePanel();
            this.siticoneCheckBox7 = new SiticoneCheckBox();
            this.siticoneCheckBox6 = new SiticoneCheckBox();
            this.siticoneCheckBox5 = new SiticoneCheckBox();
            this.label4 = new Label();
            this.siticoneCheckBox4 = new SiticoneCheckBox();
            this.siticoneCheckBox3 = new SiticoneCheckBox();
            this.siticoneCheckBox2 = new SiticoneCheckBox();
            this.siticoneCheckBox1 = new SiticoneCheckBox();
            this.bunifuButton24 = new BunifuButton2();
            this.label10 = new Label();
            this.bunifuButton23 = new BunifuButton2();
            this.label9 = new Label();
            this.siticonePanel1.SuspendLayout();
            this.siticonePanel2.SuspendLayout();
            base.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.Font = new Font("Calibri", 11.25f, FontStyle.Bold);
            this.label1.ForeColor = Color.SlateBlue;
            this.label1.Location = new Point(242, 24);
            this.label1.Name = "label1";
            this.label1.Size = new Size(90, 18);
            this.label1.TabIndex = 0;
            this.label1.Text = "tylow private";
            this.siticonePanel1.BackColor = Color.FromArgb(17, 17, 17);
            this.siticonePanel1.Controls.Add(this.bunifuButton27);
            this.siticonePanel1.Controls.Add(this.bunifuButton26);
            this.siticonePanel1.Controls.Add(this.bunifuButton25);
            this.siticonePanel1.Controls.Add(this.bunifuHScrollBar3);
            this.siticonePanel1.Controls.Add(this.label8);
            this.siticonePanel1.Controls.Add(this.bunifuHScrollBar2);
            this.siticonePanel1.Controls.Add(this.label6);
            this.siticonePanel1.Controls.Add(this.bunifuHScrollBar1);
            this.siticonePanel1.Controls.Add(this.label3);
            this.siticonePanel1.Controls.Add(this.bunifuButton22);
            this.siticonePanel1.Controls.Add(this.bunifuButton21);
            this.siticonePanel1.Controls.Add(this.label2);
            this.siticonePanel1.Location = new Point(12, 59);
            this.siticonePanel1.Name = "siticonePanel1";
            this.siticonePanel1.ShadowDecoration.Parent = this.siticonePanel1;
            this.siticonePanel1.Size = new Size(270, 212);
            this.siticonePanel1.TabIndex = 1;
            this.bunifuButton27.AllowAnimations = false;
            this.bunifuButton27.AllowMouseEffects = false;
            this.bunifuButton27.AllowToggling = false;
            this.bunifuButton27.AnimationSpeed = 200;
            this.bunifuButton27.AutoGenerateColors = false;
            this.bunifuButton27.AutoRoundBorders = false;
            this.bunifuButton27.AutoSizeLeftIcon = true;
            this.bunifuButton27.AutoSizeRightIcon = true;
            this.bunifuButton27.BackColor = Color.Transparent;
            this.bunifuButton27.BackColor1 = Color.FromArgb(17, 17, 17);
            this.bunifuButton27.BackgroundImage = (Image)componentResourceManager.GetObject("bunifuButton27.BackgroundImage");
            this.bunifuButton27.BorderStyle = 0;
            this.bunifuButton27.ButtonText = "1.00";
            this.bunifuButton27.ButtonTextMarginLeft = 0;
            this.bunifuButton27.ColorContrastOnClick = 45;
            this.bunifuButton27.ColorContrastOnHover = 45;
            this.bunifuButton27.Cursor = Cursors.Default;
            borderEdges.BottomLeft = true;
            borderEdges.BottomRight = true;
            borderEdges.TopLeft = true;
            borderEdges.TopRight = true;
            this.bunifuButton27.CustomizableEdges = borderEdges;
            this.bunifuButton27.DialogResult = DialogResult.None;
            this.bunifuButton27.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton27.DisabledFillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton27.DisabledForecolor = Color.FromArgb(168, 160, 168);
            this.bunifuButton27.FocusState = 0;
            this.bunifuButton27.Font = new Font("Calibri", 9.75f);
            this.bunifuButton27.ForeColor = Color.White;
            this.bunifuButton27.IconLeftAlign = ContentAlignment.MiddleLeft;
            this.bunifuButton27.IconLeftCursor = Cursors.Default;
            this.bunifuButton27.IconLeftPadding = new Padding(11, 3, 3, 3);
            this.bunifuButton27.IconMarginLeft = 11;
            this.bunifuButton27.IconPadding = 10;
            this.bunifuButton27.IconRightAlign = ContentAlignment.MiddleRight;
            this.bunifuButton27.IconRightCursor = Cursors.Default;
            this.bunifuButton27.IconRightPadding = new Padding(3, 3, 7, 3);
            this.bunifuButton27.IconSize = 25;
            this.bunifuButton27.IdleBorderColor = Color.Transparent;
            this.bunifuButton27.IdleBorderRadius = 3;
            this.bunifuButton27.IdleBorderThickness = 1;
            this.bunifuButton27.IdleFillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton27.IdleIconLeftImage = null;
            this.bunifuButton27.IdleIconRightImage = null;
            this.bunifuButton27.IndicateFocus = false;
            this.bunifuButton27.Location = new Point(214, 135);
            this.bunifuButton27.Name = "bunifuButton27";
            this.bunifuButton27.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton27.OnDisabledState.BorderRadius = 3;
            this.bunifuButton27.OnDisabledState.BorderStyle = 0;
            this.bunifuButton27.OnDisabledState.BorderThickness = 1;
            this.bunifuButton27.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton27.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            this.bunifuButton27.OnDisabledState.IconLeftImage = null;
            this.bunifuButton27.OnDisabledState.IconRightImage = null;
            this.bunifuButton27.onHoverState.BorderColor = Color.Transparent;
            this.bunifuButton27.onHoverState.BorderRadius = 3;
            this.bunifuButton27.onHoverState.BorderStyle = 0;
            this.bunifuButton27.onHoverState.BorderThickness = 1;
            this.bunifuButton27.onHoverState.FillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton27.onHoverState.ForeColor = Color.White;
            this.bunifuButton27.onHoverState.IconLeftImage = null;
            this.bunifuButton27.onHoverState.IconRightImage = null;
            this.bunifuButton27.OnIdleState.BorderColor = Color.Transparent;
            this.bunifuButton27.OnIdleState.BorderRadius = 3;
            this.bunifuButton27.OnIdleState.BorderStyle = 0;
            this.bunifuButton27.OnIdleState.BorderThickness = 1;
            this.bunifuButton27.OnIdleState.FillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton27.OnIdleState.ForeColor = Color.White;
            this.bunifuButton27.OnIdleState.IconLeftImage = null;
            this.bunifuButton27.OnIdleState.IconRightImage = null;
            this.bunifuButton27.OnPressedState.BorderColor = Color.Transparent;
            this.bunifuButton27.OnPressedState.BorderRadius = 3;
            this.bunifuButton27.OnPressedState.BorderStyle = 0;
            this.bunifuButton27.OnPressedState.BorderThickness = 1;
            this.bunifuButton27.OnPressedState.FillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton27.OnPressedState.ForeColor = Color.White;
            this.bunifuButton27.OnPressedState.IconLeftImage = null;
            this.bunifuButton27.OnPressedState.IconRightImage = null;
            this.bunifuButton27.Size = new Size(44, 18);
            this.bunifuButton27.TabIndex = 13;
            this.bunifuButton27.TextAlign = ContentAlignment.MiddleRight;
            this.bunifuButton27.TextAlignment = HorizontalAlignment.Center;
            this.bunifuButton27.TextMarginLeft = 0;
            this.bunifuButton27.TextPadding = new Padding(0);
            this.bunifuButton27.UseDefaultRadiusAndThickness = true;
            this.bunifuButton26.AllowAnimations = false;
            this.bunifuButton26.AllowMouseEffects = false;
            this.bunifuButton26.AllowToggling = false;
            this.bunifuButton26.AnimationSpeed = 200;
            this.bunifuButton26.AutoGenerateColors = false;
            this.bunifuButton26.AutoRoundBorders = false;
            this.bunifuButton26.AutoSizeLeftIcon = true;
            this.bunifuButton26.AutoSizeRightIcon = true;
            this.bunifuButton26.BackColor = Color.Transparent;
            this.bunifuButton26.BackColor1 = Color.FromArgb(17, 17, 17);
            this.bunifuButton26.BackgroundImage = (Image)componentResourceManager.GetObject("bunifuButton26.BackgroundImage");
            this.bunifuButton26.BorderStyle = 0;
            this.bunifuButton26.ButtonText = "1.00";
            this.bunifuButton26.ButtonTextMarginLeft = 0;
            this.bunifuButton26.ColorContrastOnClick = 45;
            this.bunifuButton26.ColorContrastOnHover = 45;
            this.bunifuButton26.Cursor = Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton26.CustomizableEdges = borderEdges2;
            this.bunifuButton26.DialogResult = DialogResult.None;
            this.bunifuButton26.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton26.DisabledFillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton26.DisabledForecolor = Color.FromArgb(168, 160, 168);
            this.bunifuButton26.FocusState = 0;
            this.bunifuButton26.Font = new Font("Calibri", 9.75f);
            this.bunifuButton26.ForeColor = Color.White;
            this.bunifuButton26.IconLeftAlign = ContentAlignment.MiddleLeft;
            this.bunifuButton26.IconLeftCursor = Cursors.Default;
            this.bunifuButton26.IconLeftPadding = new Padding(11, 3, 3, 3);
            this.bunifuButton26.IconMarginLeft = 11;
            this.bunifuButton26.IconPadding = 10;
            this.bunifuButton26.IconRightAlign = ContentAlignment.MiddleRight;
            this.bunifuButton26.IconRightCursor = Cursors.Default;
            this.bunifuButton26.IconRightPadding = new Padding(3, 3, 7, 3);
            this.bunifuButton26.IconSize = 25;
            this.bunifuButton26.IdleBorderColor = Color.Transparent;
            this.bunifuButton26.IdleBorderRadius = 3;
            this.bunifuButton26.IdleBorderThickness = 1;
            this.bunifuButton26.IdleFillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton26.IdleIconLeftImage = null;
            this.bunifuButton26.IdleIconRightImage = null;
            this.bunifuButton26.IndicateFocus = false;
            this.bunifuButton26.Location = new Point(214, 90);
            this.bunifuButton26.Name = "bunifuButton26";
            this.bunifuButton26.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton26.OnDisabledState.BorderRadius = 3;
            this.bunifuButton26.OnDisabledState.BorderStyle = 0;
            this.bunifuButton26.OnDisabledState.BorderThickness = 1;
            this.bunifuButton26.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton26.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            this.bunifuButton26.OnDisabledState.IconLeftImage = null;
            this.bunifuButton26.OnDisabledState.IconRightImage = null;
            this.bunifuButton26.onHoverState.BorderColor = Color.Transparent;
            this.bunifuButton26.onHoverState.BorderRadius = 3;
            this.bunifuButton26.onHoverState.BorderStyle = 0;
            this.bunifuButton26.onHoverState.BorderThickness = 1;
            this.bunifuButton26.onHoverState.FillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton26.onHoverState.ForeColor = Color.White;
            this.bunifuButton26.onHoverState.IconLeftImage = null;
            this.bunifuButton26.onHoverState.IconRightImage = null;
            this.bunifuButton26.OnIdleState.BorderColor = Color.Transparent;
            this.bunifuButton26.OnIdleState.BorderRadius = 3;
            this.bunifuButton26.OnIdleState.BorderStyle = 0;
            this.bunifuButton26.OnIdleState.BorderThickness = 1;
            this.bunifuButton26.OnIdleState.FillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton26.OnIdleState.ForeColor = Color.White;
            this.bunifuButton26.OnIdleState.IconLeftImage = null;
            this.bunifuButton26.OnIdleState.IconRightImage = null;
            this.bunifuButton26.OnPressedState.BorderColor = Color.Transparent;
            this.bunifuButton26.OnPressedState.BorderRadius = 3;
            this.bunifuButton26.OnPressedState.BorderStyle = 0;
            this.bunifuButton26.OnPressedState.BorderThickness = 1;
            this.bunifuButton26.OnPressedState.FillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton26.OnPressedState.ForeColor = Color.White;
            this.bunifuButton26.OnPressedState.IconLeftImage = null;
            this.bunifuButton26.OnPressedState.IconRightImage = null;
            this.bunifuButton26.Size = new Size(44, 18);
            this.bunifuButton26.TabIndex = 12;
            this.bunifuButton26.TextAlign = ContentAlignment.MiddleRight;
            this.bunifuButton26.TextAlignment = HorizontalAlignment.Center;
            this.bunifuButton26.TextMarginLeft = 0;
            this.bunifuButton26.TextPadding = new Padding(0);
            this.bunifuButton26.UseDefaultRadiusAndThickness = true;
            this.bunifuButton25.AllowAnimations = false;
            this.bunifuButton25.AllowMouseEffects = false;
            this.bunifuButton25.AllowToggling = false;
            this.bunifuButton25.AnimationSpeed = 200;
            this.bunifuButton25.AutoGenerateColors = false;
            this.bunifuButton25.AutoRoundBorders = false;
            this.bunifuButton25.AutoSizeLeftIcon = true;
            this.bunifuButton25.AutoSizeRightIcon = true;
            this.bunifuButton25.BackColor = Color.Transparent;
            this.bunifuButton25.BackColor1 = Color.FromArgb(17, 17, 17);
            this.bunifuButton25.BackgroundImage = (Image)componentResourceManager.GetObject("bunifuButton25.BackgroundImage");
            this.bunifuButton25.BorderStyle = 0;
            this.bunifuButton25.ButtonText = "12.0";
            this.bunifuButton25.ButtonTextMarginLeft = 0;
            this.bunifuButton25.ColorContrastOnClick = 45;
            this.bunifuButton25.ColorContrastOnHover = 45;
            this.bunifuButton25.Cursor = Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton25.CustomizableEdges = borderEdges3;
            this.bunifuButton25.DialogResult = DialogResult.None;
            this.bunifuButton25.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton25.DisabledFillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton25.DisabledForecolor = Color.FromArgb(168, 160, 168);
            this.bunifuButton25.FocusState = 0;
            this.bunifuButton25.Font = new Font("Calibri", 9.75f);
            this.bunifuButton25.ForeColor = Color.White;
            this.bunifuButton25.IconLeftAlign = ContentAlignment.MiddleLeft;
            this.bunifuButton25.IconLeftCursor = Cursors.Default;
            this.bunifuButton25.IconLeftPadding = new Padding(11, 3, 3, 3);
            this.bunifuButton25.IconMarginLeft = 11;
            this.bunifuButton25.IconPadding = 10;
            this.bunifuButton25.IconRightAlign = ContentAlignment.MiddleRight;
            this.bunifuButton25.IconRightCursor = Cursors.Default;
            this.bunifuButton25.IconRightPadding = new Padding(3, 3, 7, 3);
            this.bunifuButton25.IconSize = 25;
            this.bunifuButton25.IdleBorderColor = Color.Transparent;
            this.bunifuButton25.IdleBorderRadius = 3;
            this.bunifuButton25.IdleBorderThickness = 1;
            this.bunifuButton25.IdleFillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton25.IdleIconLeftImage = null;
            this.bunifuButton25.IdleIconRightImage = null;
            this.bunifuButton25.IndicateFocus = false;
            this.bunifuButton25.Location = new Point(214, 45);
            this.bunifuButton25.Name = "bunifuButton25";
            this.bunifuButton25.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton25.OnDisabledState.BorderRadius = 3;
            this.bunifuButton25.OnDisabledState.BorderStyle = 0;
            this.bunifuButton25.OnDisabledState.BorderThickness = 1;
            this.bunifuButton25.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton25.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            this.bunifuButton25.OnDisabledState.IconLeftImage = null;
            this.bunifuButton25.OnDisabledState.IconRightImage = null;
            this.bunifuButton25.onHoverState.BorderColor = Color.Transparent;
            this.bunifuButton25.onHoverState.BorderRadius = 3;
            this.bunifuButton25.onHoverState.BorderStyle = 0;
            this.bunifuButton25.onHoverState.BorderThickness = 1;
            this.bunifuButton25.onHoverState.FillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton25.onHoverState.ForeColor = Color.White;
            this.bunifuButton25.onHoverState.IconLeftImage = null;
            this.bunifuButton25.onHoverState.IconRightImage = null;
            this.bunifuButton25.OnIdleState.BorderColor = Color.Transparent;
            this.bunifuButton25.OnIdleState.BorderRadius = 3;
            this.bunifuButton25.OnIdleState.BorderStyle = 0;
            this.bunifuButton25.OnIdleState.BorderThickness = 1;
            this.bunifuButton25.OnIdleState.FillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton25.OnIdleState.ForeColor = Color.White;
            this.bunifuButton25.OnIdleState.IconLeftImage = null;
            this.bunifuButton25.OnIdleState.IconRightImage = null;
            this.bunifuButton25.OnPressedState.BorderColor = Color.Transparent;
            this.bunifuButton25.OnPressedState.BorderRadius = 3;
            this.bunifuButton25.OnPressedState.BorderStyle = 0;
            this.bunifuButton25.OnPressedState.BorderThickness = 1;
            this.bunifuButton25.OnPressedState.FillColor = Color.FromArgb(17, 17, 17);
            this.bunifuButton25.OnPressedState.ForeColor = Color.White;
            this.bunifuButton25.OnPressedState.IconLeftImage = null;
            this.bunifuButton25.OnPressedState.IconRightImage = null;
            this.bunifuButton25.Size = new Size(44, 18);
            this.bunifuButton25.TabIndex = 6;
            this.bunifuButton25.TextAlign = ContentAlignment.MiddleRight;
            this.bunifuButton25.TextAlignment = HorizontalAlignment.Center;
            this.bunifuButton25.TextMarginLeft = 0;
            this.bunifuButton25.TextPadding = new Padding(0);
            this.bunifuButton25.UseDefaultRadiusAndThickness = true;
            this.bunifuHScrollBar3.AllowCursorChanges = true;
            this.bunifuHScrollBar3.AllowHomeEndKeysDetection = false;
            this.bunifuHScrollBar3.AllowIncrementalClickMoves = true;
            this.bunifuHScrollBar3.AllowMouseDownEffects = true;
            this.bunifuHScrollBar3.AllowMouseHoverEffects = true;
            this.bunifuHScrollBar3.AllowScrollingAnimations = true;
            this.bunifuHScrollBar3.AllowScrollKeysDetection = true;
            this.bunifuHScrollBar3.AllowScrollOptionsMenu = true;
            this.bunifuHScrollBar3.AllowShrinkingOnFocusLost = false;
            this.bunifuHScrollBar3.BackgoundColor = Color.FromArgb(25, 25, 25);
            this.bunifuHScrollBar3.BackgroundImage = (Image)componentResourceManager.GetObject("bunifuHScrollBar3.BackgroundImage");
            this.bunifuHScrollBar3.BindingContainer = null;
            this.bunifuHScrollBar3.BorderColor = Color.Transparent;
            this.bunifuHScrollBar3.BorderRadius = 14;
            this.bunifuHScrollBar3.BorderThickness = 1;
            this.bunifuHScrollBar3.DurationBeforeShrink = 2000;
            this.bunifuHScrollBar3.LargeChange = 10;
            this.bunifuHScrollBar3.Location = new Point(15, 158);
            this.bunifuHScrollBar3.Maximum = 2000;
            this.bunifuHScrollBar3.Minimum = 100;
            this.bunifuHScrollBar3.MinimumThumbLength = 18;
            this.bunifuHScrollBar3.Name = "bunifuHScrollBar3";
            this.bunifuHScrollBar3.OnDisable.ScrollBarBorderColor = Color.Silver;
            this.bunifuHScrollBar3.OnDisable.ScrollBarColor = Color.Transparent;
            this.bunifuHScrollBar3.OnDisable.ThumbColor = Color.Silver;
            this.bunifuHScrollBar3.ScrollBarBorderColor = Color.Transparent;
            this.bunifuHScrollBar3.ScrollBarColor = Color.FromArgb(25, 25, 25);
            this.bunifuHScrollBar3.ShrinkSizeLimit = 3;
            this.bunifuHScrollBar3.Size = new Size(243, 19);
            this.bunifuHScrollBar3.SmallChange = 1;
            this.bunifuHScrollBar3.TabIndex = 11;
            this.bunifuHScrollBar3.ThumbColor = Color.SlateBlue;
            this.bunifuHScrollBar3.ThumbLength = 18;
            this.bunifuHScrollBar3.ThumbMargin = 1;
            this.bunifuHScrollBar3.ThumbStyle = 0;
            this.bunifuHScrollBar3.Value = 100;
            this.bunifuHScrollBar3.ValueChanged += this.bunifuHScrollBar3_ValueChanged;
            this.label8.AutoSize = true;
            this.label8.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label8.Location = new Point(15, 135);
            this.label8.Name = "label8";
            this.label8.Size = new Size(67, 15);
            this.label8.TabIndex = 9;
            this.label8.Text = "Jitter Force";
            this.bunifuHScrollBar2.AllowCursorChanges = true;
            this.bunifuHScrollBar2.AllowHomeEndKeysDetection = false;
            this.bunifuHScrollBar2.AllowIncrementalClickMoves = true;
            this.bunifuHScrollBar2.AllowMouseDownEffects = true;
            this.bunifuHScrollBar2.AllowMouseHoverEffects = true;
            this.bunifuHScrollBar2.AllowScrollingAnimations = true;
            this.bunifuHScrollBar2.AllowScrollKeysDetection = true;
            this.bunifuHScrollBar2.AllowScrollOptionsMenu = true;
            this.bunifuHScrollBar2.AllowShrinkingOnFocusLost = false;
            this.bunifuHScrollBar2.BackgoundColor = Color.FromArgb(25, 25, 25);
            this.bunifuHScrollBar2.BackgroundImage = (Image)componentResourceManager.GetObject("bunifuHScrollBar2.BackgroundImage");
            this.bunifuHScrollBar2.BindingContainer = null;
            this.bunifuHScrollBar2.BorderColor = Color.Transparent;
            this.bunifuHScrollBar2.BorderRadius = 14;
            this.bunifuHScrollBar2.BorderThickness = 1;
            this.bunifuHScrollBar2.DurationBeforeShrink = 2000;
            this.bunifuHScrollBar2.LargeChange = 10;
            this.bunifuHScrollBar2.Location = new Point(15, 113);
            this.bunifuHScrollBar2.Maximum = 500;
            this.bunifuHScrollBar2.Minimum = 100;
            this.bunifuHScrollBar2.MinimumThumbLength = 18;
            this.bunifuHScrollBar2.Name = "bunifuHScrollBar2";
            this.bunifuHScrollBar2.OnDisable.ScrollBarBorderColor = Color.Silver;
            this.bunifuHScrollBar2.OnDisable.ScrollBarColor = Color.Transparent;
            this.bunifuHScrollBar2.OnDisable.ThumbColor = Color.Silver;
            this.bunifuHScrollBar2.ScrollBarBorderColor = Color.Transparent;
            this.bunifuHScrollBar2.ScrollBarColor = Color.FromArgb(25, 25, 25);
            this.bunifuHScrollBar2.ShrinkSizeLimit = 3;
            this.bunifuHScrollBar2.Size = new Size(243, 19);
            this.bunifuHScrollBar2.SmallChange = 1;
            this.bunifuHScrollBar2.TabIndex = 8;
            this.bunifuHScrollBar2.ThumbColor = Color.SlateBlue;
            this.bunifuHScrollBar2.ThumbLength = 18;
            this.bunifuHScrollBar2.ThumbMargin = 1;
            this.bunifuHScrollBar2.ThumbStyle = 0;
            this.bunifuHScrollBar2.Value = 100;
            this.bunifuHScrollBar2.ValueChanged += this.bunifuHScrollBar2_ValueChanged;
            this.label6.AutoSize = true;
            this.label6.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label6.Location = new Point(15, 90);
            this.label6.Name = "label6";
            this.label6.Size = new Size(89, 15);
            this.label6.TabIndex = 6;
            this.label6.Text = "Randomization";
            this.bunifuHScrollBar1.AllowCursorChanges = true;
            this.bunifuHScrollBar1.AllowHomeEndKeysDetection = false;
            this.bunifuHScrollBar1.AllowIncrementalClickMoves = true;
            this.bunifuHScrollBar1.AllowMouseDownEffects = true;
            this.bunifuHScrollBar1.AllowMouseHoverEffects = true;
            this.bunifuHScrollBar1.AllowScrollingAnimations = true;
            this.bunifuHScrollBar1.AllowScrollKeysDetection = true;
            this.bunifuHScrollBar1.AllowScrollOptionsMenu = true;
            this.bunifuHScrollBar1.AllowShrinkingOnFocusLost = false;
            this.bunifuHScrollBar1.BackgoundColor = Color.FromArgb(25, 25, 25);
            this.bunifuHScrollBar1.BackgroundImage = (Image)componentResourceManager.GetObject("bunifuHScrollBar1.BackgroundImage");
            this.bunifuHScrollBar1.BindingContainer = null;
            this.bunifuHScrollBar1.BorderColor = Color.Transparent;
            this.bunifuHScrollBar1.BorderRadius = 14;
            this.bunifuHScrollBar1.BorderThickness = 1;
            this.bunifuHScrollBar1.DurationBeforeShrink = 2000;
            this.bunifuHScrollBar1.LargeChange = 10;
            this.bunifuHScrollBar1.Location = new Point(15, 68);
            this.bunifuHScrollBar1.Maximum = 2000;
            this.bunifuHScrollBar1.Minimum = 1200;
            this.bunifuHScrollBar1.MinimumThumbLength = 18;
            this.bunifuHScrollBar1.Name = "bunifuHScrollBar1";
            this.bunifuHScrollBar1.OnDisable.ScrollBarBorderColor = Color.Silver;
            this.bunifuHScrollBar1.OnDisable.ScrollBarColor = Color.Transparent;
            this.bunifuHScrollBar1.OnDisable.ThumbColor = Color.Silver;
            this.bunifuHScrollBar1.ScrollBarBorderColor = Color.Transparent;
            this.bunifuHScrollBar1.ScrollBarColor = Color.FromArgb(25, 25, 25);
            this.bunifuHScrollBar1.ShrinkSizeLimit = 3;
            this.bunifuHScrollBar1.Size = new Size(243, 19);
            this.bunifuHScrollBar1.SmallChange = 1;
            this.bunifuHScrollBar1.TabIndex = 5;
            this.bunifuHScrollBar1.ThumbColor = Color.SlateBlue;
            this.bunifuHScrollBar1.ThumbLength = 18;
            this.bunifuHScrollBar1.ThumbMargin = 1;
            this.bunifuHScrollBar1.ThumbStyle = 0;
            this.bunifuHScrollBar1.Value = 1200;
            this.bunifuHScrollBar1.ValueChanged += this.bunifuHScrollBar1_ValueChanged;
            this.label3.AutoSize = true;
            this.label3.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label3.Location = new Point(15, 45);
            this.label3.Name = "label3";
            this.label3.Size = new Size(103, 15);
            this.label3.TabIndex = 3;
            this.label3.Text = "Clicks per second";
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = false;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = false;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = Color.Transparent;
            this.bunifuButton22.BackColor1 = Color.FromArgb(22, 22, 22);
            this.bunifuButton22.BackgroundImage = (Image)componentResourceManager.GetObject("bunifuButton22.BackgroundImage");
            this.bunifuButton22.BorderStyle = 0;
            this.bunifuButton22.ButtonText = "none";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges4;
            this.bunifuButton22.DialogResult = DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton22.DisabledFillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton22.DisabledForecolor = Color.FromArgb(168, 160, 168);
            this.bunifuButton22.FocusState = 0;
            this.bunifuButton22.Font = new Font("Calibri", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.bunifuButton22.ForeColor = Color.White;
            this.bunifuButton22.IconLeftAlign = ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = Cursors.Default;
            this.bunifuButton22.IconLeftPadding = new Padding(11, 3, 3, 3);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 10;
            this.bunifuButton22.IconRightAlign = ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = Cursors.Default;
            this.bunifuButton22.IconRightPadding = new Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 25;
            this.bunifuButton22.IdleBorderColor = Color.Transparent;
            this.bunifuButton22.IdleBorderRadius = 3;
            this.bunifuButton22.IdleBorderThickness = 1;
            this.bunifuButton22.IdleFillColor = Color.FromArgb(22, 22, 22);
            this.bunifuButton22.IdleIconLeftImage = null;
            this.bunifuButton22.IdleIconRightImage = null;
            this.bunifuButton22.IndicateFocus = false;
            this.bunifuButton22.Location = new Point(194, 8);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton22.OnDisabledState.BorderRadius = 3;
            this.bunifuButton22.OnDisabledState.BorderStyle = 0;
            this.bunifuButton22.OnDisabledState.BorderThickness = 1;
            this.bunifuButton22.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton22.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = Color.SlateBlue;
            this.bunifuButton22.onHoverState.BorderRadius = 3;
            this.bunifuButton22.onHoverState.BorderStyle = 0;
            this.bunifuButton22.onHoverState.BorderThickness = 1;
            this.bunifuButton22.onHoverState.FillColor = Color.FromArgb(40, 40, 40);
            this.bunifuButton22.onHoverState.ForeColor = Color.White;
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = Color.Transparent;
            this.bunifuButton22.OnIdleState.BorderRadius = 3;
            this.bunifuButton22.OnIdleState.BorderStyle = 0;
            this.bunifuButton22.OnIdleState.BorderThickness = 1;
            this.bunifuButton22.OnIdleState.FillColor = Color.FromArgb(22, 22, 22);
            this.bunifuButton22.OnIdleState.ForeColor = Color.White;
            this.bunifuButton22.OnIdleState.IconLeftImage = null;
            this.bunifuButton22.OnIdleState.IconRightImage = null;
            this.bunifuButton22.OnPressedState.BorderColor = Color.SlateBlue;
            this.bunifuButton22.OnPressedState.BorderRadius = 3;
            this.bunifuButton22.OnPressedState.BorderStyle = 0;
            this.bunifuButton22.OnPressedState.BorderThickness = 1;
            this.bunifuButton22.OnPressedState.FillColor = Color.FromArgb(40, 40, 40);
            this.bunifuButton22.OnPressedState.ForeColor = Color.White;
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new Size(64, 28);
            this.bunifuButton22.TabIndex = 2;
            this.bunifuButton22.TextAlign = ContentAlignment.MiddleCenter;
            this.bunifuButton22.TextAlignment = HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new Padding(0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            this.bunifuButton22.Click += this.bunifuButton22_Click;
            this.bunifuButton22.KeyDown += this.bunifuButton22_KeyDown;
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = Color.Transparent;
            this.bunifuButton21.BackColor1 = Color.FromArgb(22, 22, 22);
            this.bunifuButton21.BackgroundImage = (Image)componentResourceManager.GetObject("bunifuButton21.BackgroundImage");
            this.bunifuButton21.BorderStyle = 0;
            this.bunifuButton21.ButtonText = "disable";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges5;
            this.bunifuButton21.DialogResult = DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton21.DisabledFillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton21.DisabledForecolor = Color.FromArgb(168, 160, 168);
            this.bunifuButton21.FocusState = 0;
            this.bunifuButton21.Font = new Font("Calibri", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.bunifuButton21.ForeColor = Color.White;
            this.bunifuButton21.IconLeftAlign = ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = Cursors.Default;
            this.bunifuButton21.IconRightPadding = new Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = Color.Transparent;
            this.bunifuButton21.IdleBorderRadius = 3;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = Color.FromArgb(22, 22, 22);
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new Point(124, 8);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton21.OnDisabledState.BorderRadius = 3;
            this.bunifuButton21.OnDisabledState.BorderStyle = 0;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton21.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = Color.SlateBlue;
            this.bunifuButton21.onHoverState.BorderRadius = 3;
            this.bunifuButton21.onHoverState.BorderStyle = 0;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = Color.FromArgb(40, 40, 40);
            this.bunifuButton21.onHoverState.ForeColor = Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = Color.Transparent;
            this.bunifuButton21.OnIdleState.BorderRadius = 3;
            this.bunifuButton21.OnIdleState.BorderStyle = 0;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = Color.FromArgb(22, 22, 22);
            this.bunifuButton21.OnIdleState.ForeColor = Color.White;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = Color.SlateBlue;
            this.bunifuButton21.OnPressedState.BorderRadius = 3;
            this.bunifuButton21.OnPressedState.BorderStyle = 0;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = Color.FromArgb(40, 40, 40);
            this.bunifuButton21.OnPressedState.ForeColor = Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new Size(64, 28);
            this.bunifuButton21.TabIndex = 1;
            this.bunifuButton21.TextAlign = ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += this.bunifuButton21_Click;
            this.label2.AutoSize = true;
            this.label2.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label2.ForeColor = Color.SlateBlue;
            this.label2.Location = new Point(15, 15);
            this.label2.Name = "label2";
            this.label2.Size = new Size(73, 15);
            this.label2.TabIndex = 0;
            this.label2.Text = "auto-clicker";
            this.siticonePanel2.BackColor = Color.FromArgb(17, 17, 17);
            this.siticonePanel2.Controls.Add(this.siticoneCheckBox7);
            this.siticonePanel2.Controls.Add(this.siticoneCheckBox6);
            this.siticonePanel2.Controls.Add(this.siticoneCheckBox5);
            this.siticonePanel2.Controls.Add(this.label4);
            this.siticonePanel2.Controls.Add(this.siticoneCheckBox4);
            this.siticonePanel2.Controls.Add(this.siticoneCheckBox3);
            this.siticonePanel2.Controls.Add(this.siticoneCheckBox2);
            this.siticonePanel2.Controls.Add(this.siticoneCheckBox1);
            this.siticonePanel2.Controls.Add(this.bunifuButton24);
            this.siticonePanel2.Controls.Add(this.label10);
            this.siticonePanel2.Controls.Add(this.bunifuButton23);
            this.siticonePanel2.Controls.Add(this.label9);
            this.siticonePanel2.Location = new Point(288, 59);
            this.siticonePanel2.Name = "siticonePanel2";
            this.siticonePanel2.ShadowDecoration.Parent = this.siticonePanel2;
            this.siticonePanel2.Size = new Size(270, 212);
            this.siticonePanel2.TabIndex = 2;
            this.siticoneCheckBox7.AutoSize = true;
            this.siticoneCheckBox7.CheckedState.BorderColor = Color.SlateBlue;
            this.siticoneCheckBox7.CheckedState.BorderRadius = 2;
            this.siticoneCheckBox7.CheckedState.BorderThickness = 0;
            this.siticoneCheckBox7.CheckedState.FillColor = Color.SlateBlue;
            this.siticoneCheckBox7.CheckMarkColor = Color.Transparent;
            this.siticoneCheckBox7.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.siticoneCheckBox7.Location = new Point(18, 180);
            this.siticoneCheckBox7.Name = "siticoneCheckBox7";
            this.siticoneCheckBox7.Size = new Size(108, 19);
            this.siticoneCheckBox7.TabIndex = 15;
            this.siticoneCheckBox7.Text = "Randomization";
            this.siticoneCheckBox7.UncheckedState.BorderColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox7.UncheckedState.BorderRadius = 2;
            this.siticoneCheckBox7.UncheckedState.BorderThickness = 0;
            this.siticoneCheckBox7.UncheckedState.FillColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox7.UseVisualStyleBackColor = true;
            this.siticoneCheckBox6.AutoSize = true;
            this.siticoneCheckBox6.CheckedState.BorderColor = Color.SlateBlue;
            this.siticoneCheckBox6.CheckedState.BorderRadius = 2;
            this.siticoneCheckBox6.CheckedState.BorderThickness = 0;
            this.siticoneCheckBox6.CheckedState.FillColor = Color.SlateBlue;
            this.siticoneCheckBox6.CheckMarkColor = Color.Transparent;
            this.siticoneCheckBox6.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.siticoneCheckBox6.Location = new Point(18, 155);
            this.siticoneCheckBox6.Name = "siticoneCheckBox6";
            this.siticoneCheckBox6.Size = new Size(78, 19);
            this.siticoneCheckBox6.TabIndex = 14;
            this.siticoneCheckBox6.Text = "Inventory";
            this.siticoneCheckBox6.UncheckedState.BorderColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox6.UncheckedState.BorderRadius = 2;
            this.siticoneCheckBox6.UncheckedState.BorderThickness = 0;
            this.siticoneCheckBox6.UncheckedState.FillColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox6.UseVisualStyleBackColor = true;
            this.siticoneCheckBox5.AutoSize = true;
            this.siticoneCheckBox5.CheckedState.BorderColor = Color.SlateBlue;
            this.siticoneCheckBox5.CheckedState.BorderRadius = 2;
            this.siticoneCheckBox5.CheckedState.BorderThickness = 0;
            this.siticoneCheckBox5.CheckedState.FillColor = Color.SlateBlue;
            this.siticoneCheckBox5.CheckMarkColor = Color.Transparent;
            this.siticoneCheckBox5.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.siticoneCheckBox5.Location = new Point(140, 105);
            this.siticoneCheckBox5.Name = "siticoneCheckBox5";
            this.siticoneCheckBox5.Size = new Size(91, 19);
            this.siticoneCheckBox5.TabIndex = 13;
            this.siticoneCheckBox5.Text = "Timer Mode";
            this.siticoneCheckBox5.UncheckedState.BorderColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox5.UncheckedState.BorderRadius = 2;
            this.siticoneCheckBox5.UncheckedState.BorderThickness = 0;
            this.siticoneCheckBox5.UncheckedState.FillColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox5.UseVisualStyleBackColor = true;
            this.siticoneCheckBox5.CheckedChanged += this.siticoneCheckBox5_CheckedChanged;
            this.label4.AutoSize = true;
            this.label4.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label4.ForeColor = Color.SlateBlue;
            this.label4.Location = new Point(15, 75);
            this.label4.Name = "label4";
            this.label4.Size = new Size(65, 15);
            this.label4.TabIndex = 12;
            this.label4.Text = "conditions";
            this.siticoneCheckBox4.AutoSize = true;
            this.siticoneCheckBox4.CheckedState.BorderColor = Color.SlateBlue;
            this.siticoneCheckBox4.CheckedState.BorderRadius = 2;
            this.siticoneCheckBox4.CheckedState.BorderThickness = 0;
            this.siticoneCheckBox4.CheckedState.FillColor = Color.SlateBlue;
            this.siticoneCheckBox4.CheckMarkColor = Color.Transparent;
            this.siticoneCheckBox4.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.siticoneCheckBox4.Location = new Point(140, 155);
            this.siticoneCheckBox4.Name = "siticoneCheckBox4";
            this.siticoneCheckBox4.Size = new Size(94, 19);
            this.siticoneCheckBox4.TabIndex = 11;
            this.siticoneCheckBox4.Text = "No Hit Delay";
            this.siticoneCheckBox4.UncheckedState.BorderColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox4.UncheckedState.BorderRadius = 2;
            this.siticoneCheckBox4.UncheckedState.BorderThickness = 0;
            this.siticoneCheckBox4.UncheckedState.FillColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox4.UseVisualStyleBackColor = true;
            this.siticoneCheckBox4.CheckedChanged += this.siticoneCheckBox4_CheckedChanged;
            this.siticoneCheckBox3.AutoSize = true;
            this.siticoneCheckBox3.CheckedState.BorderColor = Color.SlateBlue;
            this.siticoneCheckBox3.CheckedState.BorderRadius = 2;
            this.siticoneCheckBox3.CheckedState.BorderThickness = 0;
            this.siticoneCheckBox3.CheckedState.FillColor = Color.SlateBlue;
            this.siticoneCheckBox3.CheckMarkColor = Color.Transparent;
            this.siticoneCheckBox3.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.siticoneCheckBox3.Location = new Point(18, 130);
            this.siticoneCheckBox3.Name = "siticoneCheckBox3";
            this.siticoneCheckBox3.Size = new Size(53, 19);
            this.siticoneCheckBox3.TabIndex = 10;
            this.siticoneCheckBox3.Text = "Jitter";
            this.siticoneCheckBox3.UncheckedState.BorderColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox3.UncheckedState.BorderRadius = 2;
            this.siticoneCheckBox3.UncheckedState.BorderThickness = 0;
            this.siticoneCheckBox3.UncheckedState.FillColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox3.UseVisualStyleBackColor = true;
            this.siticoneCheckBox2.AutoSize = true;
            this.siticoneCheckBox2.CheckedState.BorderColor = Color.SlateBlue;
            this.siticoneCheckBox2.CheckedState.BorderRadius = 2;
            this.siticoneCheckBox2.CheckedState.BorderThickness = 0;
            this.siticoneCheckBox2.CheckedState.FillColor = Color.SlateBlue;
            this.siticoneCheckBox2.CheckMarkColor = Color.Transparent;
            this.siticoneCheckBox2.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.siticoneCheckBox2.Location = new Point(140, 130);
            this.siticoneCheckBox2.Name = "siticoneCheckBox2";
            this.siticoneCheckBox2.Size = new Size(90, 19);
            this.siticoneCheckBox2.TabIndex = 9;
            this.siticoneCheckBox2.Text = "Block Break";
            this.siticoneCheckBox2.UncheckedState.BorderColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox2.UncheckedState.BorderRadius = 2;
            this.siticoneCheckBox2.UncheckedState.BorderThickness = 0;
            this.siticoneCheckBox2.UncheckedState.FillColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox2.UseVisualStyleBackColor = true;
            this.siticoneCheckBox2.CheckedChanged += this.siticoneCheckBox2_CheckedChanged;
            this.siticoneCheckBox1.AutoSize = true;
            this.siticoneCheckBox1.CheckedState.BorderColor = Color.SlateBlue;
            this.siticoneCheckBox1.CheckedState.BorderRadius = 2;
            this.siticoneCheckBox1.CheckedState.BorderThickness = 0;
            this.siticoneCheckBox1.CheckedState.FillColor = Color.SlateBlue;
            this.siticoneCheckBox1.CheckMarkColor = Color.Transparent;
            this.siticoneCheckBox1.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.siticoneCheckBox1.Location = new Point(18, 105);
            this.siticoneCheckBox1.Name = "siticoneCheckBox1";
            this.siticoneCheckBox1.Size = new Size(100, 19);
            this.siticoneCheckBox1.TabIndex = 8;
            this.siticoneCheckBox1.Text = "Blatant Mode";
            this.siticoneCheckBox1.UncheckedState.BorderColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox1.UncheckedState.BorderRadius = 2;
            this.siticoneCheckBox1.UncheckedState.BorderThickness = 0;
            this.siticoneCheckBox1.UncheckedState.FillColor = Color.FromArgb(25, 25, 25);
            this.siticoneCheckBox1.UseVisualStyleBackColor = true;
            this.siticoneCheckBox1.CheckedChanged += this.siticoneCheckBox1_CheckedChanged;
            this.bunifuButton24.AllowAnimations = true;
            this.bunifuButton24.AllowMouseEffects = true;
            this.bunifuButton24.AllowToggling = false;
            this.bunifuButton24.AnimationSpeed = 200;
            this.bunifuButton24.AutoGenerateColors = false;
            this.bunifuButton24.AutoRoundBorders = false;
            this.bunifuButton24.AutoSizeLeftIcon = true;
            this.bunifuButton24.AutoSizeRightIcon = true;
            this.bunifuButton24.BackColor = Color.Transparent;
            this.bunifuButton24.BackColor1 = Color.FromArgb(22, 22, 22);
            this.bunifuButton24.BackgroundImage = (Image)componentResourceManager.GetObject("bunifuButton24.BackgroundImage");
            this.bunifuButton24.BorderStyle = 0;
            this.bunifuButton24.ButtonText = "none";
            this.bunifuButton24.ButtonTextMarginLeft = 0;
            this.bunifuButton24.ColorContrastOnClick = 45;
            this.bunifuButton24.ColorContrastOnHover = 45;
            this.bunifuButton24.Cursor = Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButton24.CustomizableEdges = borderEdges6;
            this.bunifuButton24.DialogResult = DialogResult.None;
            this.bunifuButton24.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton24.DisabledFillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton24.DisabledForecolor = Color.FromArgb(168, 160, 168);
            this.bunifuButton24.FocusState = 0;
            this.bunifuButton24.Font = new Font("Calibri", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.bunifuButton24.ForeColor = Color.White;
            this.bunifuButton24.IconLeftAlign = ContentAlignment.MiddleLeft;
            this.bunifuButton24.IconLeftCursor = Cursors.Default;
            this.bunifuButton24.IconLeftPadding = new Padding(11, 3, 3, 3);
            this.bunifuButton24.IconMarginLeft = 11;
            this.bunifuButton24.IconPadding = 10;
            this.bunifuButton24.IconRightAlign = ContentAlignment.MiddleRight;
            this.bunifuButton24.IconRightCursor = Cursors.Default;
            this.bunifuButton24.IconRightPadding = new Padding(3, 3, 7, 3);
            this.bunifuButton24.IconSize = 25;
            this.bunifuButton24.IdleBorderColor = Color.Transparent;
            this.bunifuButton24.IdleBorderRadius = 3;
            this.bunifuButton24.IdleBorderThickness = 1;
            this.bunifuButton24.IdleFillColor = Color.FromArgb(22, 22, 22);
            this.bunifuButton24.IdleIconLeftImage = null;
            this.bunifuButton24.IdleIconRightImage = null;
            this.bunifuButton24.IndicateFocus = false;
            this.bunifuButton24.Location = new Point(194, 38);
            this.bunifuButton24.Name = "bunifuButton24";
            this.bunifuButton24.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton24.OnDisabledState.BorderRadius = 3;
            this.bunifuButton24.OnDisabledState.BorderStyle = 0;
            this.bunifuButton24.OnDisabledState.BorderThickness = 1;
            this.bunifuButton24.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton24.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            this.bunifuButton24.OnDisabledState.IconLeftImage = null;
            this.bunifuButton24.OnDisabledState.IconRightImage = null;
            this.bunifuButton24.onHoverState.BorderColor = Color.SlateBlue;
            this.bunifuButton24.onHoverState.BorderRadius = 3;
            this.bunifuButton24.onHoverState.BorderStyle = 0;
            this.bunifuButton24.onHoverState.BorderThickness = 1;
            this.bunifuButton24.onHoverState.FillColor = Color.FromArgb(40, 40, 40);
            this.bunifuButton24.onHoverState.ForeColor = Color.White;
            this.bunifuButton24.onHoverState.IconLeftImage = null;
            this.bunifuButton24.onHoverState.IconRightImage = null;
            this.bunifuButton24.OnIdleState.BorderColor = Color.Transparent;
            this.bunifuButton24.OnIdleState.BorderRadius = 3;
            this.bunifuButton24.OnIdleState.BorderStyle = 0;
            this.bunifuButton24.OnIdleState.BorderThickness = 1;
            this.bunifuButton24.OnIdleState.FillColor = Color.FromArgb(22, 22, 22);
            this.bunifuButton24.OnIdleState.ForeColor = Color.White;
            this.bunifuButton24.OnIdleState.IconLeftImage = null;
            this.bunifuButton24.OnIdleState.IconRightImage = null;
            this.bunifuButton24.OnPressedState.BorderColor = Color.SlateBlue;
            this.bunifuButton24.OnPressedState.BorderRadius = 3;
            this.bunifuButton24.OnPressedState.BorderStyle = 0;
            this.bunifuButton24.OnPressedState.BorderThickness = 1;
            this.bunifuButton24.OnPressedState.FillColor = Color.FromArgb(40, 40, 40);
            this.bunifuButton24.OnPressedState.ForeColor = Color.White;
            this.bunifuButton24.OnPressedState.IconLeftImage = null;
            this.bunifuButton24.OnPressedState.IconRightImage = null;
            this.bunifuButton24.Size = new Size(64, 28);
            this.bunifuButton24.TabIndex = 7;
            this.bunifuButton24.TextAlign = ContentAlignment.MiddleCenter;
            this.bunifuButton24.TextAlignment = HorizontalAlignment.Center;
            this.bunifuButton24.TextMarginLeft = 0;
            this.bunifuButton24.TextPadding = new Padding(0);
            this.bunifuButton24.UseDefaultRadiusAndThickness = true;
            this.bunifuButton24.Click += this.bunifuButton24_Click;
            this.bunifuButton24.KeyDown += this.bunifuButton24_KeyDown;
            this.label10.AutoSize = true;
            this.label10.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label10.Location = new Point(15, 45);
            this.label10.Name = "label10";
            this.label10.Size = new Size(75, 15);
            this.label10.TabIndex = 6;
            this.label10.Text = "Destruct Key";
            this.bunifuButton23.AllowAnimations = true;
            this.bunifuButton23.AllowMouseEffects = true;
            this.bunifuButton23.AllowToggling = false;
            this.bunifuButton23.AnimationSpeed = 200;
            this.bunifuButton23.AutoGenerateColors = false;
            this.bunifuButton23.AutoRoundBorders = false;
            this.bunifuButton23.AutoSizeLeftIcon = true;
            this.bunifuButton23.AutoSizeRightIcon = true;
            this.bunifuButton23.BackColor = Color.Transparent;
            this.bunifuButton23.BackColor1 = Color.FromArgb(22, 22, 22);
            this.bunifuButton23.BackgroundImage = (Image)componentResourceManager.GetObject("bunifuButton23.BackgroundImage");
            this.bunifuButton23.BorderStyle = 0;
            this.bunifuButton23.ButtonText = "none";
            this.bunifuButton23.ButtonTextMarginLeft = 0;
            this.bunifuButton23.ColorContrastOnClick = 45;
            this.bunifuButton23.ColorContrastOnHover = 45;
            this.bunifuButton23.Cursor = Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButton23.CustomizableEdges = borderEdges7;
            this.bunifuButton23.DialogResult = DialogResult.None;
            this.bunifuButton23.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton23.DisabledFillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton23.DisabledForecolor = Color.FromArgb(168, 160, 168);
            this.bunifuButton23.FocusState = 0;
            this.bunifuButton23.Font = new Font("Calibri", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.bunifuButton23.ForeColor = Color.White;
            this.bunifuButton23.IconLeftAlign = ContentAlignment.MiddleLeft;
            this.bunifuButton23.IconLeftCursor = Cursors.Default;
            this.bunifuButton23.IconLeftPadding = new Padding(11, 3, 3, 3);
            this.bunifuButton23.IconMarginLeft = 11;
            this.bunifuButton23.IconPadding = 10;
            this.bunifuButton23.IconRightAlign = ContentAlignment.MiddleRight;
            this.bunifuButton23.IconRightCursor = Cursors.Default;
            this.bunifuButton23.IconRightPadding = new Padding(3, 3, 7, 3);
            this.bunifuButton23.IconSize = 25;
            this.bunifuButton23.IdleBorderColor = Color.Transparent;
            this.bunifuButton23.IdleBorderRadius = 3;
            this.bunifuButton23.IdleBorderThickness = 1;
            this.bunifuButton23.IdleFillColor = Color.FromArgb(22, 22, 22);
            this.bunifuButton23.IdleIconLeftImage = null;
            this.bunifuButton23.IdleIconRightImage = null;
            this.bunifuButton23.IndicateFocus = false;
            this.bunifuButton23.Location = new Point(194, 8);
            this.bunifuButton23.Name = "bunifuButton23";
            this.bunifuButton23.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            this.bunifuButton23.OnDisabledState.BorderRadius = 3;
            this.bunifuButton23.OnDisabledState.BorderStyle = 0;
            this.bunifuButton23.OnDisabledState.BorderThickness = 1;
            this.bunifuButton23.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            this.bunifuButton23.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            this.bunifuButton23.OnDisabledState.IconLeftImage = null;
            this.bunifuButton23.OnDisabledState.IconRightImage = null;
            this.bunifuButton23.onHoverState.BorderColor = Color.SlateBlue;
            this.bunifuButton23.onHoverState.BorderRadius = 3;
            this.bunifuButton23.onHoverState.BorderStyle = 0;
            this.bunifuButton23.onHoverState.BorderThickness = 1;
            this.bunifuButton23.onHoverState.FillColor = Color.FromArgb(40, 40, 40);
            this.bunifuButton23.onHoverState.ForeColor = Color.White;
            this.bunifuButton23.onHoverState.IconLeftImage = null;
            this.bunifuButton23.onHoverState.IconRightImage = null;
            this.bunifuButton23.OnIdleState.BorderColor = Color.Transparent;
            this.bunifuButton23.OnIdleState.BorderRadius = 3;
            this.bunifuButton23.OnIdleState.BorderStyle = 0;
            this.bunifuButton23.OnIdleState.BorderThickness = 1;
            this.bunifuButton23.OnIdleState.FillColor = Color.FromArgb(22, 22, 22);
            this.bunifuButton23.OnIdleState.ForeColor = Color.White;
            this.bunifuButton23.OnIdleState.IconLeftImage = null;
            this.bunifuButton23.OnIdleState.IconRightImage = null;
            this.bunifuButton23.OnPressedState.BorderColor = Color.SlateBlue;
            this.bunifuButton23.OnPressedState.BorderRadius = 3;
            this.bunifuButton23.OnPressedState.BorderStyle = 0;
            this.bunifuButton23.OnPressedState.BorderThickness = 1;
            this.bunifuButton23.OnPressedState.FillColor = Color.FromArgb(40, 40, 40);
            this.bunifuButton23.OnPressedState.ForeColor = Color.White;
            this.bunifuButton23.OnPressedState.IconLeftImage = null;
            this.bunifuButton23.OnPressedState.IconRightImage = null;
            this.bunifuButton23.Size = new Size(64, 28);
            this.bunifuButton23.TabIndex = 5;
            this.bunifuButton23.TextAlign = ContentAlignment.MiddleCenter;
            this.bunifuButton23.TextAlignment = HorizontalAlignment.Center;
            this.bunifuButton23.TextMarginLeft = 0;
            this.bunifuButton23.TextPadding = new Padding(0);
            this.bunifuButton23.UseDefaultRadiusAndThickness = true;
            this.bunifuButton23.Click += this.bunifuButton23_Click;
            this.bunifuButton23.KeyDown += this.bunifuButton23_KeyDown;
            this.label9.AutoSize = true;
            this.label9.Font = new Font("Calibri", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label9.Location = new Point(15, 15);
            this.label9.Name = "label9";
            this.label9.Size = new Size(54, 15);
            this.label9.TabIndex = 4;
            this.label9.Text = "Hide Key";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.FromArgb(15, 15, 15);
            base.ClientSize = new Size(570, 283);
            base.Controls.Add(this.siticonePanel2);
            base.Controls.Add(this.siticonePanel1);
            base.Controls.Add(this.label1);
            this.Font = new Font("Calibri", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.ForeColor = Color.White;
            base.FormBorderStyle = FormBorderStyle.FixedSingle;
            base.MaximizeBox = false;
            base.Name = "Form1";
            base.ShowIcon = false;
            this.siticonePanel1.ResumeLayout(false);
            this.siticonePanel1.PerformLayout();
            this.siticonePanel2.ResumeLayout(false);
            this.siticonePanel2.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        private Label label1;
        private SiticonePanel siticonePanel1;
        private BunifuButton2 bunifuButton27;
        private BunifuButton2 bunifuButton26;
        private BunifuButton2 bunifuButton25;
        private BunifuHScrollBar bunifuHScrollBar3;
        private Label label8;
        private BunifuHScrollBar bunifuHScrollBar2;
        private Label label6;
        private BunifuHScrollBar bunifuHScrollBar1;
        private Label label3;
        private BunifuButton2 bunifuButton22;
        private BunifuButton2 bunifuButton21;
        private Label label2;
        private SiticonePanel siticonePanel2;
        private SiticoneCheckBox siticoneCheckBox7;
        private SiticoneCheckBox siticoneCheckBox6;
        private SiticoneCheckBox siticoneCheckBox5;
        private Label label4;
        private SiticoneCheckBox siticoneCheckBox4;
        private SiticoneCheckBox siticoneCheckBox3;
        private SiticoneCheckBox siticoneCheckBox2;
        private SiticoneCheckBox siticoneCheckBox1;
        private BunifuButton2 bunifuButton24;
        private Label label10;
        private BunifuButton2 bunifuButton23;
        private Label label9;

        #endregion
    }
}
